# qmlib/app/Cargo.toml
[package]
name = "qmlib_apps"
version = "0.1.0"
edition = "2021"

[dependencies]
qmlib = { path = "../lib" }  # Local path to the library
binrw = "0.14.0"
nalgebra = "0.33.0"

[[bin]]
name = "tile_info"
path = "src/tile_info.rs"
args = [
    "<path>",
]

[[bin]]
name = "export_kml"
path = "src/export_kml.rs"
args = [
    "<path>",
]

[[bin]]
name = "export_svg"
path = "src/export_svg.rs"
args = [
    "<path>",
]

[[bin]]
name = "export_geotiff"
path = "src/export_geotiff.rs"
args = [
    "<path>",
    "<N>", # bitwise n scale shift
]