[package]
name = "qmlib_compute_shader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]


[dependencies]
glam = "0.29.0"
spirv-std = { path = "../../rust-gpu/crates/spirv-std", version = "=0.9.0", features = ["bytemuck"] }
